version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - .:/code
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
