# Generated by Django 4.2.15 on 2024-08-22 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberverification',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. Разрешено от 9 до 15 .", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
